const r=require('express').Router();const db=require('../config/database');const bcrypt=require('bcrypt');r.use(require('../middlewares/authMiddleware').somenteAdm);
r.get('/responsaveis',async(req,res)=>{const [responsaveis]=await db.query('SELECT idResp,nome,email,telefone,cpf,foto FROM usuario_Resp ORDER BY nome');const [vinculos]=await db.query('SELECT idResp,idAluno FROM aluno_respo');res.json({responsaveis,vinculos});});
r.post('/responsaveis',require('../controllers/usuarioController').cadastrarResponsavel);
r.put('/responsaveis/:id',async(req,res)=>{const {nome,email,telefone,cpf,foto,senha}=req.body;if(!nome||!email)return res.status(400).json({mensagem:'Nome e e-mail obrigatórios.'});try{await db.execute('UPDATE usuario_Resp SET nome=?,email=?,telefone=?,cpf=?,foto=? WHERE idResp=?',[nome,email,telefone||null,cpf||null,foto||null,req.params.id]);if(senha)await db.execute('UPDATE usuario_Resp SET senha=? WHERE idResp=?',[await bcrypt.hash(senha,10),req.params.id]);res.json({sucesso:true});}catch(e){res.status(409).json({mensagem:'Não foi possível salvar. Verifique se o e-mail já existe.'});}});
r.delete('/responsaveis/:id',async(req,res)=>{await db.execute('DELETE FROM usuario_Resp WHERE idResp=?',[req.params.id]);res.json({sucesso:true});});
r.post('/vinculos',async(req,res)=>{try{await db.execute('INSERT IGNORE INTO aluno_respo (idResp,idAluno) VALUES (?,?)',[req.body.idResp,req.body.idAluno]);res.json({sucesso:true});}catch(e){res.status(400).json({mensagem:'Selecione responsável e aluno válidos.'});}});
r.delete('/vinculos/:idResp/:idAluno',async(req,res)=>{await db.execute('DELETE FROM aluno_respo WHERE idResp=? AND idAluno=?',[req.params.idResp,req.params.idAluno]);res.json({sucesso:true});});
r.get('/intervalos',async(req,res)=>{const [intervalos]=await db.query('SELECT * FROM intervalo ORDER BY horarioInicio');res.json({intervalos});});
async function salvarIntervalo(req,res){const {nome,horarioInicio,horarioFim}=req.body;if(!nome||!/^\d{2}:\d{2}$/.test(horarioInicio)||!/^\d{2}:\d{2}$/.test(horarioFim)||horarioFim<=horarioInicio)return res.status(400).json({mensagem:'Informe um nome e horários válidos (fim após início).'});if(req.params.id)await db.execute('UPDATE intervalo SET nome=?,horarioInicio=?,horarioFim=? WHERE idIntervalo=?',[nome,horarioInicio,horarioFim,req.params.id]);else await db.execute('INSERT INTO intervalo (nome,horarioInicio,horarioFim) VALUES (?,?,?)',[nome,horarioInicio,horarioFim]);res.json({sucesso:true});}
r.post('/intervalos',salvarIntervalo);r.put('/intervalos/:id',salvarIntervalo);r.delete('/intervalos/:id',async(req,res)=>{await db.execute('DELETE FROM intervalo WHERE idIntervalo=?',[req.params.id]);res.json({sucesso:true});});module.exports=r;
