USE Cantina_CMD;
ALTER TABLE usuario_Adm MODIFY senha VARCHAR(255) NOT NULL, MODIFY email VARCHAR(120) NOT NULL;
ALTER TABLE usuario_Resp MODIFY senha VARCHAR(255) NOT NULL, MODIFY email VARCHAR(120) NOT NULL;
ALTER TABLE usuario_Aluno MODIFY senha VARCHAR(255) NOT NULL, MODIFY email VARCHAR(120) NOT NULL, MODIFY turma VARCHAR(30) NOT NULL;
ALTER TABLE conta_Aluno MODIFY limiteNegativo DECIMAL(10,2) NOT NULL DEFAULT 250.00;
ALTER TABLE item_Pedido MODIFY quantidade INT NOT NULL DEFAULT 1;
ALTER TABLE cardapio MODIFY dataCardapio DATE NOT NULL;
ALTER TABLE intervalo CHANGE horarioFIm horarioFim TIME NOT NULL;
ALTER TABLE produto MODIFY disponivel CHAR(1) NOT NULL DEFAULT 'S';
ALTER TABLE pedido MODIFY retirado CHAR(1) NOT NULL DEFAULT 'N';

ALTER TABLE usuario_Adm ADD COLUMN foto LONGTEXT NULL, ADD COLUMN criadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE usuario_Resp ADD COLUMN cpf VARCHAR(14) NULL, ADD COLUMN telefone VARCHAR(20) NULL, ADD COLUMN foto LONGTEXT NULL, ADD COLUMN criadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE usuario_Aluno ADD COLUMN foto LONGTEXT NULL, ADD COLUMN criadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE conta_Aluno ADD COLUMN limiteDiario DECIMAL(10,2) NOT NULL DEFAULT 25.00;
ALTER TABLE movimento_Conta ADD COLUMN tipo ENUM('DEPOSITO','COMPRA','AJUSTE','ESTORNO') NOT NULL DEFAULT 'AJUSTE' AFTER idConta, ADD COLUMN descricao VARCHAR(180) NULL AFTER valor;
ALTER TABLE movimento_Conta MODIFY dataHora DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE produto ADD COLUMN categoria VARCHAR(40) NOT NULL DEFAULT 'Outros' AFTER descricao, ADD COLUMN imagem LONGTEXT NULL, ADD COLUMN criadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE estoque ADD COLUMN estoqueMinimo DECIMAL(10,2) NOT NULL DEFAULT 5;
ALTER TABLE pedido ADD COLUMN dataHoraPedido DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER idAluno, ADD COLUMN status ENUM('PENDENTE','PREPARANDO','PRONTO','RETIRADO','CANCELADO') NOT NULL DEFAULT 'PENDENTE' AFTER dataHoraPedido;
ALTER TABLE pedido MODIFY tipoVenda ENUM('ANTECIPADA','BALCAO') NOT NULL DEFAULT 'ANTECIPADA';

ALTER TABLE usuario_Adm ADD UNIQUE KEY uq_adm_email (email);
ALTER TABLE usuario_Resp ADD UNIQUE KEY uq_resp_email (email);
ALTER TABLE usuario_Aluno ADD UNIQUE KEY uq_aluno_email (email);
ALTER TABLE conta_Aluno ADD UNIQUE KEY uq_conta_aluno (idAluno);
ALTER TABLE estoque ADD UNIQUE KEY uq_estoque_produto (idProd);
ALTER TABLE cardapio ADD UNIQUE KEY uq_cardapio_data (dataCardapio);
ALTER TABLE item_Cardapio ADD UNIQUE KEY uq_item_cardapio (idCard,idProd);
ALTER TABLE pedido ADD UNIQUE KEY uq_codigo_retirada (codigoRetirada);

INSERT IGNORE INTO intervalo (idIntervalo, nome, horarioInicio, horarioFim) VALUES
(1, '1º intervalo', '09:00:00', '09:20:00'),
(2, '2º intervalo', '15:00:00', '15:20:00');
ALTER TABLE pedido MODIFY idIntervalo INT NULL;
