const db=require('../config/database');
function codigo(){return Math.random().toString(36).slice(2,8).toUpperCase();}
async function intervalos(req,res){try{const [rows]=await db.query('SELECT * FROM intervalo ORDER BY horarioInicio');res.json({sucesso:true,intervalos:rows});}catch(e){res.status(500).json({sucesso:false,mensagem:'Erro ao listar intervalos.'});}}
async function criar(req,res){const idAluno=req.session.usuario.tipo==='adm'?req.body.idAluno:req.session.usuario.id;const {itens,idIntervalo,tipoVenda='ANTECIPADA'}=req.body;if(!idAluno)return res.status(400).json({sucesso:false,mensagem:'Informe o aluno.'});if(!Array.isArray(itens)||!itens.length)return res.status(400).json({sucesso:false,mensagem:'Carrinho vazio.'});if(itens.some(i=>!i||!Number.isSafeInteger(Number(i.idProd))||Number(i.idProd)<=0||!Number.isSafeInteger(Number(i.quantidade))||Number(i.quantidade)<=0||Number(i.quantidade)>9999)||new Set(itens.map(i=>Number(i.idProd))).size!==itens.length)return res.status(400).json({sucesso:false,mensagem:'Itens ou quantidades inválidos. Não repita produtos.'});if(!['ANTECIPADA','BALCAO'].includes(tipoVenda)||(req.session.usuario.tipo!=='adm'&&tipoVenda==='BALCAO'))return res.status(400).json({sucesso:false,mensagem:'Tipo de venda inválido.'});const conn=await db.getConnection();try{await conn.beginTransaction();if(tipoVenda==='ANTECIPADA'){const [int]=await conn.execute('SELECT idIntervalo FROM intervalo WHERE idIntervalo=?',[idIntervalo||null]);if(!int.length)throw new Error('Selecione um intervalo de retirada cadastrado.');}const [contas]=await conn.execute('SELECT * FROM conta_Aluno WHERE idAluno=? FOR UPDATE',[idAluno]);if(!contas.length)throw new Error('Conta não encontrada.');let total=0;const itensDb=[];for(const item of itens){const [p]=await conn.execute(`SELECT p.idProd,p.nome,p.preco,p.disponivel,e.quantidade FROM produto p JOIN estoque e ON e.idProd=p.idProd WHERE p.idProd=? FOR UPDATE`,[item.idProd]);if(!p.length||p[0].disponivel!=='S'||Number(p[0].quantidade)<Number(item.quantidade))throw new Error(`Produto indisponível: ${p[0]?.nome||item.idProd}`);const q=Number(item.quantidade)||1;total+=Number(p[0].preco)*q;itensDb.push({...p[0],quantidade:q});}
const conta=contas[0];const novoSaldo=Number(conta.saldo)-total;if(novoSaldo < -Number(conta.limiteNegativo)) throw new Error('Saldo insuficiente para esta compra.');const [gasto]=await conn.execute("SELECT COALESCE(SUM(valorTotal),0) total FROM pedido WHERE idAluno=? AND status<>'CANCELADO' AND DATE(dataHoraPedido)=CURDATE()",[idAluno]);if(Number(gasto[0].total)+total>Number(conta.limiteDiario))throw new Error('Limite diário excedido.');const cod=codigo();const [r]=await conn.execute('INSERT INTO pedido (idIntervalo,idAluno,status,retirado,tipoVenda,codigoRetirada,valorTotal) VALUES (?,? ,\'PENDENTE\',\'N\',?,?,?)',[idIntervalo||null,idAluno,tipoVenda,cod,total]);for(const item of itensDb){await conn.execute('INSERT INTO item_Pedido (idPedido,idProd,quantidade,precoUnitario) VALUES (?,?,?,?)',[r.insertId,item.idProd,item.quantidade,item.preco]);await conn.execute('UPDATE estoque SET quantidade=quantidade-? WHERE idProd=?',[item.quantidade,item.idProd]);}
await conn.execute('UPDATE conta_Aluno SET saldo=? WHERE idConta=?',[novoSaldo,conta.idConta]);await conn.execute("INSERT INTO movimento_Conta (idConta,tipo,valor,descricao) VALUES (?,'COMPRA',?,?)",[conta.idConta,-total,`Pedido #${r.insertId}`]);await conn.commit();res.status(201).json({sucesso:true,mensagem:'Pedido realizado.',idPedido:r.insertId,codigoRetirada:cod,valorTotal:total});}catch(e){await conn.rollback();console.error(e);res.status(400).json({sucesso:false,mensagem:e.message||'Erro ao criar pedido.'});}finally{conn.release();}}
async function meus(req,res){try{const [rows]=await db.execute(`SELECT p.*,i.nome intervalo,i.horarioInicio,GROUP_CONCAT(ip.quantidade || 'x ' || pr.nome, ', ') itens FROM pedido p LEFT JOIN intervalo i ON i.idIntervalo=p.idIntervalo JOIN item_Pedido ip ON ip.idPedido=p.idPedido JOIN produto pr ON pr.idProd=ip.idProd WHERE p.idAluno=? GROUP BY p.idPedido ORDER BY p.dataHoraPedido DESC`,[req.session.usuario.id]);res.json({sucesso:true,pedidos:rows});}catch(e){res.status(500).json({sucesso:false,mensagem:'Erro ao carregar pedidos.'});}}
async function listar(req,res){try{const {status,busca}=req.query;let sql=`SELECT p.*,a.nome aluno,a.turma,i.nome intervalo,i.horarioInicio,GROUP_CONCAT(ip.quantidade || 'x ' || pr.nome, ', ') itens FROM pedido p JOIN usuario_Aluno a ON a.idAluno=p.idAluno LEFT JOIN intervalo i ON i.idIntervalo=p.idIntervalo JOIN item_Pedido ip ON ip.idPedido=p.idPedido JOIN produto pr ON pr.idProd=ip.idProd WHERE 1=1`;const params=[];if(status){sql+=' AND p.status=?';params.push(status);}if(busca){sql+=' AND (a.nome LIKE ? OR p.codigoRetirada LIKE ? OR pr.nome LIKE ?)';params.push(`%${busca}%`,`%${busca}%`,`%${busca}%`);}sql+=' GROUP BY p.idPedido ORDER BY p.dataHoraPedido DESC';const [rows]=await db.execute(sql,params);res.json({sucesso:true,pedidos:rows});}catch(e){console.error(e);res.status(500).json({sucesso:false,mensagem:'Erro ao listar pedidos.'});}}
async function status(req,res){
 const st=req.body.status,transicoes={PENDENTE:['PREPARANDO','CANCELADO'],PREPARANDO:['PRONTO','CANCELADO'],PRONTO:['RETIRADO','CANCELADO'],RETIRADO:[],CANCELADO:[]};
 if(!Object.hasOwn(transicoes,st))return res.status(400).json({sucesso:false,mensagem:'Status inválido.'});
 const conn=await db.getConnection();
 try{await conn.beginTransaction();const [rows]=await conn.execute('SELECT * FROM pedido WHERE idPedido=? FOR UPDATE',[req.params.id]);const p=rows[0];if(!p||!transicoes[p.status].includes(st))throw new Error('Transição de status inválida ou pedido já atualizado.');
 if(st==='CANCELADO'){const [contas]=await conn.execute('SELECT idConta FROM conta_Aluno WHERE idAluno=? FOR UPDATE',[p.idAluno]);const [itens]=await conn.execute('SELECT idProd,quantidade FROM item_Pedido WHERE idPedido=?',[p.idPedido]);for(const i of itens)await conn.execute('UPDATE estoque SET quantidade=quantidade+? WHERE idProd=?',[i.quantidade,i.idProd]);await conn.execute('UPDATE conta_Aluno SET saldo=saldo+? WHERE idConta=?',[p.valorTotal,contas[0].idConta]);await conn.execute("INSERT INTO movimento_Conta (idConta,tipo,valor,descricao) VALUES (?,'ESTORNO',?,?)",[contas[0].idConta,p.valorTotal,'Cancelamento do pedido #'+p.idPedido]);}
 await conn.execute('UPDATE pedido SET status=?,retirado=? WHERE idPedido=?',[st,st==='RETIRADO'?'S':'N',p.idPedido]);await conn.commit();res.json({sucesso:true,mensagem:'Status atualizado.'});}catch(e){await conn.rollback();res.status(409).json({sucesso:false,mensagem:e.message});}finally{conn.release();}
}

module.exports={intervalos,criar,meus,listar,status};
