function valido(b){return typeof b.nome==='string'&&b.nome.trim()&&b.nome.length<=80&&Number.isFinite(Number(b.preco))&&Number(b.preco)>=0&&Number(b.preco)<=999999.99&&Number.isInteger(Number(b.quantidade??0))&&Number(b.quantidade??0)>=0&&Number.isFinite(Number(b.estoqueMinimo??5))&&Number(b.estoqueMinimo??5)>=0&&['S','N'].includes(b.disponivel||'S');}
const db=require('../config/database');
async function listar(req,res){try{const [rows]=await db.query(`SELECT p.*,COALESCE(e.quantidade,0) quantidade,COALESCE(e.estoqueMinimo,5) estoqueMinimo FROM produto p LEFT JOIN estoque e ON e.idProd=p.idProd ORDER BY p.nome`);res.json({sucesso:true,produtos:rows});}catch(e){console.error(e);res.status(500).json({sucesso:false,mensagem:'Erro ao listar produtos.'});}}
async function disponiveis(req,res){try{const [rows]=await db.query(`SELECT p.*,COALESCE(e.quantidade,0) quantidade FROM produto p LEFT JOIN estoque e ON e.idProd=p.idProd WHERE p.disponivel='S' AND COALESCE(e.quantidade,0)>0 ORDER BY p.categoria,p.nome`);res.json({sucesso:true,produtos:rows});}catch(e){res.status(500).json({sucesso:false,mensagem:'Erro ao carregar cardápio.'});}}
async function criar(req,res){if(!valido(req.body))return res.status(400).json({sucesso:false,mensagem:'Informe nome, preço e estoque válidos.'});const {nome,descricao,categoria,preco,disponivel,imagem,quantidade,estoqueMinimo}=req.body;const conn=await db.getConnection();try{await conn.beginTransaction();const [r]=await conn.execute('INSERT INTO produto (nome,descricao,categoria,preco,disponivel,imagem) VALUES (?,?,?,?,?,?)',[nome,descricao||null,categoria||'Outros',preco,disponivel||'S',imagem||null]);await conn.execute('INSERT INTO estoque (idProd,quantidade,estoqueMinimo) VALUES (?,?,?)',[r.insertId,quantidade||0,estoqueMinimo??5]);await conn.commit();res.status(201).json({sucesso:true,mensagem:'Produto criado.',idProd:r.insertId});}catch(e){await conn.rollback();console.error(e);res.status(500).json({sucesso:false,mensagem:'Erro ao criar produto.'});}finally{conn.release();}}
async function editar(req,res){if(!valido(req.body))return res.status(400).json({sucesso:false,mensagem:'Informe nome, preço e estoque válidos.'});const {nome,descricao,categoria,preco,disponivel,imagem,quantidade,estoqueMinimo}=req.body;const conn=await db.getConnection();try{await conn.beginTransaction();await conn.execute('UPDATE produto SET nome=?,descricao=?,categoria=?,preco=?,disponivel=?,imagem=? WHERE idProd=?',[nome,descricao||null,categoria||'Outros',preco,disponivel||'S',imagem||null,req.params.id]);await conn.execute('INSERT INTO estoque (idProd,quantidade,estoqueMinimo) VALUES (?,?,?) ON CONFLICT(idProd) DO UPDATE SET quantidade=excluded.quantidade, estoqueMinimo=excluded.estoqueMinimo',[req.params.id,quantidade||0,estoqueMinimo??5]);await conn.commit();res.json({sucesso:true,mensagem:'Produto atualizado.'});}catch(e){await conn.rollback();console.error(e);res.status(500).json({sucesso:false,mensagem:'Erro ao atualizar produto.'});}finally{conn.release();}}
async function excluir(req,res){try{await db.execute('DELETE FROM produto WHERE idProd=?',[req.params.id]);res.json({sucesso:true,mensagem:'Produto excluído.'});}catch(e){console.error(e);res.status(409).json({sucesso:false,mensagem:'Produto possui pedidos e não pode ser excluído.'});}}
async function atualizarEstoque(req,res){try{const {quantidade,estoqueMinimo}=req.body;if(!Number.isInteger(Number(quantidade))||Number(quantidade)<0||!Number.isFinite(Number(estoqueMinimo??5))||Number(estoqueMinimo??5)<0)return res.status(400).json({sucesso:false,mensagem:'Informe quantidades válidas.'});await db.execute('INSERT INTO estoque (idProd,quantidade,estoqueMinimo) VALUES (?,?,?) ON CONFLICT(idProd) DO UPDATE SET quantidade=excluded.quantidade,estoqueMinimo=excluded.estoqueMinimo',[req.params.id,quantidade,estoqueMinimo??5]);await db.execute("UPDATE produto SET disponivel=CASE WHEN ?>0 THEN 'S' ELSE 'N' END WHERE idProd=?",[quantidade,req.params.id]);res.json({sucesso:true,mensagem:'Estoque atualizado.'});}catch(e){console.error(e);res.status(500).json({sucesso:false,mensagem:'Erro ao atualizar estoque.'});}}
module.exports={listar,disponiveis,criar,editar,excluir,atualizarEstoque};
